/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import clases.clientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RYZEN 7
 */
public class frmClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClientes
     */
      DefaultTableModel modelox;
    public frmClientes() {
        initComponents();
      mtdPrepararTablaClientes();
    }
private void mtdPrepararTablaClientes(){
    String titulos []={"Identificación","Nombres", "Correo", "Dirección", "Celular"};
modelox = new DefaultTableModel(null, titulos);
tablaClientes.setModel(modelox);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnEliminarFIila = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setText("Registro de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 190, 72));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("Cédula o RUC:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtCedula.setBackground(new java.awt.Color(204, 255, 204));
        txtCedula.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtCedula.setBorder(null);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 270, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Nombres:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtNombres.setBackground(new java.awt.Color(204, 255, 204));
        txtNombres.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 270, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 270, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtEmail.setBackground(new java.awt.Color(204, 255, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 270, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(204, 255, 204));
        txtDireccion.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 270, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtCelular.setBackground(new java.awt.Color(204, 255, 204));
        txtCelular.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtCelular.setBorder(null);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 270, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Género:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtGenero.setBackground(new java.awt.Color(204, 255, 204));
        txtGenero.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtGenero.setBorder(null);
        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 270, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Saldo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtSaldo.setBackground(new java.awt.Color(204, 255, 204));
        txtSaldo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtSaldo.setBorder(null);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 270, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 270, 10));

        btnRegistrar.setBackground(new java.awt.Color(102, 255, 51));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 530, 480));

        btnEliminarFIila.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminarFIila.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEliminarFIila.setText("Eliminar");
        btnEliminarFIila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFIilaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarFIila, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 120, 40));

        btnEditar.setBackground(new java.awt.Color(102, 153, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private static boolean ga=false;

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    clases.clientes obj = new clientes(Integer.parseInt(txtCedula.getText()), txtNombres.getText(), txtEmail.getText(), txtDireccion.getText(), Integer.parseInt(txtCelular.getText()), txtGenero.getText(), Integer.parseInt(txtSaldo.getText()));
    if(txtCedula.getText().length()>0){
    if(txtNombres.getText().length()>0){
    if(txtEmail.getText().length()>0){
    if(txtDireccion.getText().length()>0){  
    if(txtCelular.getText().length()>0){
    if(txtGenero.getText().length()>0){   
    if(txtSaldo.getText().length()>0){    
    if (ga==false){
        modelox= (DefaultTableModel) tablaClientes.getModel();
String nuevFilaa[]={String.valueOf(obj.getCedulaRUC()), obj.getNombres(),obj.getCorreo(), obj.getDireccion(), String.valueOf(obj.getCelular()),obj.getGenero(), String.valueOf(obj.getSaldo())};
    modelox.addRow(nuevFilaa);
    mtdLimpiar();
//txtRespuestaClientes.setText(obj.medDatos());
    }//GEN-LAST:event_btnRegistrarActionPerformed
    if (ga==true){
    int filasel=tablaClientes.getSelectedRow();
    if (filasel==-1){
        JOptionPane.showMessageDialog(null,"Seleccione una fila" );
    }else{
        tablaClientes.setValueAt(txtCedula.getText(), filasel, 0);
        tablaClientes.setValueAt(txtNombres.getText(), filasel, 1);
        tablaClientes.setValueAt(txtEmail.getText(), filasel, 2);
        tablaClientes.setValueAt(txtDireccion.getText(), filasel, 3);
        tablaClientes.setValueAt(txtCelular.getText(), filasel, 4);
        tablaClientes.setValueAt(txtGenero.getText(), filasel, 5);
        tablaClientes.setValueAt(txtSaldo.getText(), filasel, 6);
        ga=false;
        mtdLimpiar();
    }
}
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite el saldo","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite el género","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite el número de celular","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite la dirección","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite el email","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite los nombres","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }else{
    JOptionPane.showMessageDialog(null, "Por favor dijite la cédula","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);    
    }
    }
    private void mtdLimpiar(){
    txtCedula.setText("");
    txtNombres.setText("");
    txtEmail.setText("");
    txtDireccion.setText("");
    txtCelular.setText("");
    txtGenero.setText("");
    txtSaldo.setText("");
    
}
    private void btnEliminarFIilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFIilaActionPerformed
        int filasel = tablaClientes.getSelectedRow();
        if (filasel==-1){
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada, para continuar debe seleccionar una");
        }else{
            modelox=(DefaultTableModel) tablaClientes.getModel();
            modelox.removeRow(filasel);
        }
    }//GEN-LAST:event_btnEliminarFIilaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
               int filasel = tablaClientes.getSelectedRow();
        if (filasel==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila!");
        }else{
            txtCedula.setText(tablaClientes.getValueAt(filasel, 0).toString());
            txtNombres.setText(tablaClientes.getValueAt(filasel, 1).toString());
            txtEmail.setText(tablaClientes.getValueAt(filasel, 2).toString());
            txtDireccion.setText(tablaClientes.getValueAt(filasel, 3).toString());
            txtCelular.setText(tablaClientes.getValueAt(filasel, 4).toString());
            txtGenero.setText(tablaClientes.getValueAt(filasel, 5).toString());
            txtSaldo.setText(tablaClientes.getValueAt(filasel, 6).toString());
            ga=true;
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminarFIila;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
