/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import javax.swing.table.DefaultTableModel;
import clases.categoria;
import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN 7
 */
public class frmCategoria extends javax.swing.JInternalFrame {

  DefaultTableModel modeloxx;
    public frmCategoria() {
        
        initComponents();
        mtdPrepararTabla();
    }
private void mtdPrepararTabla(){
    String titulos []={"ID","Nombre","Descripción"};
modeloxx=new DefaultTableModel(null,titulos);
tablaCategoria.setModel(modeloxx);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        txtDescripCategoria = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategoria = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CATEGORIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 6, 150, -1));

        jLabel2.setText("Nombre de categoria:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setText("Descripcion categoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setText("ID categoria:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNombreCategoria.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, -1));

        txtDescripCategoria.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtDescripCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 110));

        txtIdCategoria.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(txtIdCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        tablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCategoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static boolean ga= false;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        clases.categoria obj = new clases.categoria(txtIdCategoria.getText(), txtNombreCategoria.getText(), txtDescripCategoria.getText());
if(txtIdCategoria.getText().length()>0){
        if(txtNombreCategoria.getText().length()>0){
            if(txtDescripCategoria.getText().length()>0){        
if (ga==false){
            modeloxx= (DefaultTableModel) tablaCategoria.getModel(); 
            String nuevaFila[]={obj.getIdCategoria(),obj.getNombreCategoria(),obj.getDescripcionCategoria()};
            modeloxx.addRow(nuevaFila);
        }
        if (ga==true){
            int filasel=tablaCategoria.getSelectedRow();
    if(filasel==-1){
        JOptionPane.showMessageDialog(null, "Por favor seleccione una fila","error",JOptionPane.INFORMATION_MESSAGE);
    }else{
        tablaCategoria.setValueAt(txtIdCategoria.getText(),filasel,0);
        tablaCategoria.setValueAt(txtNombreCategoria.getText(),filasel, 1);
        tablaCategoria.setValueAt(txtDescripCategoria.getText(), filasel, 2);
        ga=false;
        mtdLimpiar();
    }
        }
        }else{
          JOptionPane.showMessageDialog(null, "Por favor ingrese la descripción de la categoria","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        }else{
          JOptionPane.showMessageDialog(null,"Por favor ingrese el nombre de la categoria","Error",JOptionPane.INFORMATION_MESSAGE);
        }
        }else{
          JOptionPane.showMessageDialog(null, "Ingrese el ID de la categoria","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filasel = tablaCategoria.getSelectedRow();
        if (filasel==-1){
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada, para continuar debe seleccionar una","error",JOptionPane.INFORMATION_MESSAGE);
        }else{
            modeloxx=(DefaultTableModel) tablaCategoria.getModel();
            modeloxx.removeRow(filasel);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
                 int filasel = tablaCategoria.getSelectedRow();
        if (filasel==-1){
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila!","Sistema de Canchas",JOptionPane.INFORMATION_MESSAGE);
        }else{
            txtIdCategoria.setText(tablaCategoria.getValueAt(filasel, 0).toString());
            txtNombreCategoria.setText(tablaCategoria.getValueAt(filasel, 1).toString());
txtDescripCategoria.setText(tablaCategoria.getValueAt(filasel, 2).toString());


        ga = true;
        }
    }//GEN-LAST:event_btnEditarActionPerformed
private void mtdLimpiar(){
    txtIdCategoria.setText("");
    txtNombreCategoria.setText("");
    txtDescripCategoria.setText("");

    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCategoria;
    private javax.swing.JTextField txtDescripCategoria;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
