/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RYZEN 7
 */
public class frmListas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListas
     */
    DefaultListModel modelo=new DefaultListModel();
    
    public frmListas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnAct = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 102));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jScrollPane1.setViewportView(lista1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 360, 200));

        jLabel1.setText("Ingrese un pais: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        getContentPane().add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 40));

        btnEditar.setBackground(new java.awt.Color(255, 255, 153));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        btnAct.setBackground(new java.awt.Color(0, 255, 255));
        btnAct.setText("Actualizar");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });
        getContentPane().add(btnAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       if(txtPais.getText().length()>0){
           modelo.addElement(txtPais.getText());
lista1.setModel(modelo);
txtPais.setText("");
              }else{
           JOptionPane.showMessageDialog(null, "Por favor debe de ingresar un nombre de país para continuar");
       }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
int filasel=lista1.getSelectedIndex();
if(filasel==-1){
    JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
}else{
    modelo=(DefaultListModel)lista1.getModel();
    modelo.remove(filasel);
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      int filasel=lista1.getSelectedIndex();
if(filasel==-1){
    JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
}else{
    modelo=(DefaultListModel)lista1.getModel();
    txtPais.setText(modelo.getElementAt(filasel).toString());
}  
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        // TODO add your handling code here:
              int filasel=lista1.getSelectedIndex();
if(filasel==-1){
    JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
}else{
    modelo=(DefaultListModel)lista1.getModel();
    modelo.setElementAt(txtPais.getText(), filasel);
    txtPais.setText("");
}  
    }//GEN-LAST:event_btnActActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
                      int filasel=lista1.getSelectedIndex();
if(filasel==-1){
    JOptionPane.showMessageDialog(null, "Por favor seleccione una fila");
}else{
    modelo=(DefaultListModel)lista1.getModel();
    modelo.add(filasel+1, txtPais.getText());
    lista1.setModel(modelo);
    
    txtPais.setText("");
}  
    }//GEN-LAST:event_btnInsertarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAct;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista1;
    private javax.swing.JTextField txtPais;
    // End of variables declaration//GEN-END:variables
}
